# Generated by Django 2.1.1 on 2018-09-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField()),
                ('imdb_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=10, max_digits=12)),
                ('birth', models.DateField()),
                ('birthplace', models.CharField(max_length=50)),
                ('biography', models.CharField(max_length=1000)),
                ('picture', models.CharField(max_length=50)),
            ],
        ),
    ]
