# Generated by Django 2.1.1 on 2018-09-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='biography',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
